#ifndef HTTP_SERVER_HTML_H
#define HTTP_SERVER_HTML_H

PROGMEM const char HTTP_SERVER_HTML[] =
"<section id=\"userinput\">\n"
"  <h1>Global Ripple Attributes</h1>\n"
"  <p><a href=\"http://192.168.1.241/ManualRipple\"><button class=\"button\">Fire Ripple</button></a></p>\n"
"  <form action=\"/updateInternalVariables\" method=\"post\">\n"
"    <div class=\"attribute\">\n"
"      <label for=\"currentStartingNode\">Enter the starting node(s):</label>\n"
"      <select id=\"currentStartingNode\" name=\"currentStartingNode\">\n"
"        <option selected=\"selected\" value=\"center\">Center nodes</option>\n"
"        <option value=\"bi\">Bi-nodes</option>\n"
"        <option value=\"tri\">Tri-nodes</option>\n"
"        <option value=\"quad\">Quad-nodes</option>\n"
"        <option value=\"custom\">Custom</option>\n"
"      </select>\n"
"    </div>\n"
"    <div>\n"
"      <label for=\"currentBehavior\">Enter the desired behavior:</label>\n"
"      <select id=\"currentBehavior\" name=\"currentBehavior\">\n"
"        <option value=\"0\">Wide turns</option>\n"
"        <option selected=\"selected\" value=\"1\">Normal</option>\n"
"        <option value=\"2\">Tight turns</option>\n"
"        <option value=\"3\">Always turn right</option>\n"
"        <option value=\"4\">Always turn left</option>\n"
"      </select>\n"
"    </div>\n"
"    <div>\n"
"      <label for=\"currentDirection\">Enter ripple direction:</label>\n"
"      <select id=\"currentDirection\" name=\"currentDirection\">\n"
"        <option selected=\"selected\" value=\"-1\">All directions</option>\n"
"        <option value=\"0\">0°</option>\n"
"        <option value=\"1\">60°</option>\n"
"        <option value=\"2\">120°</option>\n"
"        <option value=\"3\">180°</option>\n"
"        <option value=\"4\">240°</option>\n"
"        <option value=\"5\">300°</option>\n"
"      </select>\n"
"    </div>\n"
"    <div>\n"
"      <label for=\"currentDelayBetweenRipples\">Enter delay between ripples in ms [1 - 60000]:</label>\n"
"      <input id=\"currentDelayBetweenRipples\" max=\"60000\" min=\"1\" name=\"currentDelayBetweenRipples\" type=\"number\"\n"
"        value=\"3000\" />\n"
"    </div>\n"
"    <div>\n"
"      <label for=\"currentRippleLifeSpan\">Enter ripple life span in ms [1 - 60000]:</label>\n"
"      <input id=\"currentRippleLifeSpan\" max=\"60000\" min=\"1\" name=\"currentRippleLifeSpan\" type=\"number\" value=\"3000\" />\n"
"    </div>\n"
"    <div class=\"rangeslider\">\n"
"      <label for=\"currentRippleSpeed\">Enter ripple speed [0.01 - 5]:</label>\n"
"      <input id=\"currentRippleSpeed\" max=\"500\" min=\"1.00\" name=\"currentRippleSpeed\" type=\"range\" value=\"50.00\" />\n"
"      <span id=\"currentRippleSpeed_display\">0.5</span>\n"
"    </div>\n"
"    <div>\n"
"      <label for=\"currentDecay\">Enter decay per tick [0.90 - 1]:</label>\n"
"      <input id=\"currentDecay\" max=\"1000\" min=\"900.00\" name=\"currentDecay\" type=\"range\" value=\"985.00\" />\n"
"      <span id=\"currentDecay_display\">0.985</span>\n"
"    </div>\n"
"    <div>\n"
"      <label for=\"currentColor\">Starting Color:</label>\n"
"      <div class=\"selected-color\" id=\"currentColor\" name=\"color\" value=\"#ff000\"></div>\n"
"    </div>\n"
"    <div>\n"
"      <label for=\"currentRainbowDeltaPerPeriod\">Enter hue delta per period [0 - 60000]:</label>\n"
"      <input id=\"currentRainbowDeltaPerPeriod\" max=\"60000\" min=\"0\" name=\"currentRainbowDeltaPerPeriod\" type=\"number\"\n"
"        value=\"0\" />\n"
"    </div>\n"
"    <div class=\"rangeslider\">\n"
"      <label for=\"currentRainbowDeltaPerTick\">Enter hue delta per tick [0 - 500]:</label>\n"
"      <input id=\"currentRainbowDeltaPerTick\" max=\"500\" min=\"0\" name=\"currentRainbowDeltaPerTick\" type=\"range\"\n"
"        value=\"200\" />\n"
"      <span id=\"currentRainbowDeltaPerTick_display\">200</span>\n"
"    </div>\n"
"    <div class=\"rangeslider\">\n"
"      <label for=\"currentNumberofColors\">Enter the desired number of colors [1 - 64]:</label>\n"
"      <input id=\"currentNumberofColors\" max=\"10\" min=\"1\" name=\"currentNumberofColors\" type=\"range\" value=\"7\" />\n"
"      <span id=\"currentNumberofColors_display\">7</span>\n"
"    </div>\n"
"    <div>\n"
"    </div>\n"
"    <div id=\"userinputButtons\">\n"
"      <button class=\"userinputButton\" onclick=\"sendData()\" type=\"button\">Submit</button>\n"
"      <button class=\"userinputButton\" onclick=\"discardData()\" style=\"background-color: rgb(255, 0, 0);\"\n"
"        type=\"button\">Discard changes</button>\n"
"    </div>\n"
"  </form>\n"
"</section>\n"
"<section class=\"advancedRippleManagement\">\n"
"  <div id=\"ripplesList\">\n"
"  </div>\n"
"  <button id=\"addButton\">Add Ripple</button>\n"
"  <button id=\"clearAllButton\">Clear All</button>\n"
"  <!-- Popup for editing -->\n"
"  <div class=\"popup\" id=\"editPopup\">\n"
"    <h2>Edit Ripple</h2>\n"
"    <div class=\"attribute\">\n"
"      <input id=\"editableStartingNode\" type=\"checkbox\" />\n"
"      <span>Starting Node:</span>\n"
"      <select id=\"editStartingNode\" name=\"startingNode\">\n"
"        <option value=\"center\">Center nodes</option>\n"
"        <option value=\"bi\">Bi-nodes</option>\n"
"        <option value=\"tri\">Tri-nodes</option>\n"
"        <option value=\"quad\">Quad-nodes</option>\n"
"        <option value=\"custom\">Custom</option>\n"
"      </select>\n"
"    </div>\n"
"    <div class=\"attribute\">\n"
"      <input id=\"editableBehavior\" type=\"checkbox\" />\n"
"      <span>Behavior:</span>\n"
"      <select id=\"editBehavior\" name=\"behavior\">\n"
"        <option value=\"0\">Wide turns</option>\n"
"        <option value=\"1\">Normal</option>\n"
"        <option value=\"2\">Tight turns</option>\n"
"        <option value=\"3\">Always turn right</option>\n"
"        <option value=\"4\">Always turn left</option>\n"
"      </select>\n"
"    </div>\n"
"    <div class=\"attribute\">\n"
"      <input id=\"editableDirection\" type=\"checkbox\" />\n"
"      <span>Direction:</span>\n"
"      <select id=\"editDirection\" name=\"direction\">\n"
"        <option value=\"-1\">All directions</option>\n"
"        <option value=\"0\">0°</option>\n"
"        <option value=\"1\">60°</option>\n"
"        <option value=\"2\">120°</option>\n"
"        <option value=\"3\">180°</option>\n"
"        <option value=\"4\">240°</option>\n"
"        <option value=\"5\">300°</option>\n"
"      </select>\n"
"    </div>\n"
"    <div class=\"attribute\">\n"
"      <input id=\"editablePeriod\" type=\"checkbox\" />\n"
"      <span>Period (ms):</span>\n"
"      <input id=\"editPeriod\" max=\"60000\" min=\"1\" name=\"period\" type=\"number\" value=\"3000\" />\n"
"    </div>\n"
"    <div class=\"attribute\">\n"
"      <input checked=\"\" id=\"editableOffset\" type=\"checkbox\" />\n"
"      <span>Offset (ms):</span>\n"
"      <input id=\"editOffset\" max=\"15000\" min=\"1\" name=\"offset\" type=\"number\" value=\"0\" />\n"
"    </div>\n"
"    <div class=\"attribute\">\n"
"      <input id=\"editableLifespan\" type=\"checkbox\" />\n"
"      <span>Lifespan (ms):</span>\n"
"      <input id=\"editLifespan\" max=\"60000\" min=\"1\" name=\"lifespan\" type=\"number\" value=\"3000\" />\n"
"    </div>\n"
"    <div class=\"attribute\">\n"
"      <input id=\"editableDecay\" type=\"checkbox\" />\n"
"      <span>Decay:</span>\n"
"      <input id=\"editDecay\" max=\"1\" min=\"0.9\" name=\"decay\" step=\"0.001\" type=\"number\" value=\"0.985\" />\n"
"    </div>\n"
"    <div class=\"attribute\">\n"
"      <input id=\"editableSpeed\" type=\"checkbox\" />\n"
"      <span>Speed:</span>\n"
"      <input id=\"editSpeed\" max=\"10\" min=\"0.01\" name=\"speed\" step=\"0.01\" type=\"number\" value=\"0.5\" />\n"
"    </div>\n"
"    <div class=\"attribute\">\n"
"      <input id=\"editableColor\" type=\"checkbox\" />\n"
"      <span>Color:</span>\n"
"      <div class=\"selected-color\" id=\"editColor\" name=\"color\" value=\"ff0000\"></div>\n"
"    </div>\n"
"    <div class=\"attribute\">\n"
"      <input id=\"editablehueDeltaPerTick\" type=\"checkbox\" />\n"
"      <span>hueDeltaPerTick:</span>\n"
"      <input id=\"edithueDeltaPerTick\" max=\"500\" min=\"0\" name=\"hueDeltaPerTick\" type=\"number\" value=\"200\" />\n"
"    </div>\n"
"    <div class=\"attribute\">\n"
"      <input id=\"editablehueDeltaPerPeriod\" type=\"checkbox\" />\n"
"      <span>hueDeltaPerPeriod:</span>\n"
"      <input id=\"edithueDeltaPerPeriod\" max=\"60000\" min=\"0\" name=\"hueDeltaPerPeriod\" type=\"number\" value=\"0\" />\n"
"    </div>\n"
"    <div class=\"attribute\">\n"
"      <input id=\"editablehueSteps\" type=\"checkbox\" />\n"
"      <span>hueSteps:</span>\n"
"      <input id=\"edithueSteps\" max=\"64\" min=\"0\" name=\"hueSteps\" type=\"number\" value=\"0\" />\n"
"    </div>\n"
"    <h5> if property is not checked, global setting will be used instead </h5>\n"
"    <div class=\"buttons\">\n"
"      <button id=\"saveButton\">Save Changes</button>\n"
"      <button id=\"cancelButton\">Cancel</button>\n"
"    </div>\n"
"  </div>\n"
"</section>\n"
"<div id=\"colorPicker_popup\">\n"
"  <div class=\"colorPicker_container\">\n"
"    <div class=\"colorjoe\">\n"
"      <h2>Color: </h2>\n"
"      <div id=\"selected-color-text\"></div>\n"
"      <div class=\"buttons\">\n"
"        <button id=\"saveColorPicker\">Save</button>\n"
"        <button id=\"closeColorPicker\">Close</button>\n"
"      </div>\n"
"    </div>\n"
"  </div>\n"
"</div>";


#endif /* HTTP_SERVER_HTML_H */