#ifndef HTTP_SERVER_CSS_H
#define HTTP_SERVER_CSS_H

PROGMEM const char HTTP_SERVER_CSS[] =
"<style>\n"
"    html {\n"
"      font-family: Helvetica;\n"
"      display: inline-block;\n"
"      margin: 0px auto;\n"
"      text-align: center;\n"
"    }\n"
"\n"
"\n"
"    section {\n"
"      outline: solid;\n"
"      outline-width: thin;\n"
"      margin: 1px;\n"
"      padding: 5px;\n"
"    }\n"
"\n"
"\n"
"    form div {\n"
"      display: flex;\n"
"      justify-content: space-between;\n"
"      margin: 10px 0;\n"
"    }\n"
"\n"
"    form div label {\n"
"      flex: 1;\n"
"      text-align: left;\n"
"    }\n"
"\n"
"    form div input {\n"
"      flex: 1;\n"
"      text-align: right;\n"
"    }\n"
"  </style>\n"
"<style>#rgbValue, #hslaValue {\n"
"    float: right;\n"
"}\n"
"\n"
".cj-container {\n"
"    overflow: auto;\n"
"}\n"
"\n"
"#showPicker {\n"
"    float: left;\n"
"}\n"
"\n"
".colorPicker {\n"
"    display: none;\n"
"    position: fixed;\n"
"    top: 50%;\n"
"    left: 50%;\n"
"    transform: translate(-50%, -50%);\n"
"    padding: 20px;\n"
"    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\n"
"    z-index: 1000;\n"
"    background: #ffffff;\n"
"    border: 1px solid #BBB;\n"
"    -moz-border-radius: .3em;\n"
"    border-radius: .3em;\n"
"    margin: 1em;\n"
"}\n"
"\n"
".colorPicker .extras {\n"
"    float: right;\n"
"    margin: 0.5em;\n"
"}\n"
"\n"
".colorPicker .extras .currentColorContainer {\n"
"    overflow: hidden;\n"
"}\n"
"\n"
".colorPicker .extras .currentColor {\n"
"    float: right;\n"
"    width: 65px;\n"
"    height: 30px;\n"
"    border: 1px solid #BBB;\n"
"    -moz-border-radius: .3em;\n"
"    border-radius: .3em;\n"
"}\n"
"\n"
".colorPicker .extras .colorFields {\n"
"    margin-top: 0.5em;\n"
"    margin-bottom: 0.5em;\n"
"}\n"
"\n"
".colorPicker .extras .color {\n"
"    text-align: right;\n"
"}\n"
"\n"
".colorPicker .extras .colorFields input {\n"
"    width: 40px;\n"
"    margin-left: 0.5em;\n"
"}\n"
"\n"
".colorPicker .extras .hex {\n"
"    float: right;\n"
"}\n"
"\n"
".colorPicker .extras .hex input {\n"
"    width: 60px;\n"
"}\n"
"\n"
".colorPicker .twod {\n"
"    float: left;\n"
"    margin: 0.5em;\n"
"}\n"
"\n"
"/* main dimensions */\n"
".colorPicker .twod, .colorPicker .twod .bg {\n"
"    width: 240px;\n"
"    height: 240px;\n"
"}\n"
".colorPicker .oned, .colorPicker .oned .bg {\n"
"    height: 240px;\n"
"}\n"
".colorPicker .oned, .colorPicker .oned .bg, .colorPicker .oned .pointer .shape {\n"
"    width: 20px;\n"
"}\n"
"\n"
".colorPicker .twod .bg {\n"
"    position: absolute;\n"
"\n"
"    /* These seem to cause issues in some browsers, careful!\n"
"    border: 1px solid #BBB;\n"
"    -moz-border-radius: .3em;\n"
"    border-radius: .3em;\n"
"    */\n"
"}\n"
".colorPicker .twod .pointer {\n"
"    position: relative;\n"
"    z-index: 2;\n"
"    width: 8px;\n"
"}\n"
".colorPicker .twod .pointer .shape {\n"
"    position: absolute;\n"
"}\n"
".colorPicker .twod .pointer .shape1 {\n"
"    -webkit-transform: translate(-50%, -50%);\n"
"    -ms-transform: translate(-50%, -50%);\n"
"    transform: translate(-50%, -50%);\n"
"    width: 10px;\n"
"    height: 10px;\n"
"    border: 2px solid black;\n"
"    -moz-border-radius: 5px;\n"
"    border-radius: 5px;\n"
"}\n"
".colorPicker .twod .pointer .shape2 {\n"
"    -webkit-transform: translate(-50%, -50%);\n"
"    -ms-transform: translate(-50%, -50%);\n"
"    transform: translate(-50%, -50%);\n"
"    width: 8px;\n"
"    height: 8px;\n"
"    border: 2px solid white;\n"
"    -moz-border-radius: 4px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
".colorPicker .oned {\n"
"    float: left;\n"
"    margin: 0.5em;\n"
"}\n"
"\n"
".colorPicker .oned .bg {\n"
"    border: 1px solid #BBB;\n"
"    /*\n"
"    -moz-border-radius: .3em;\n"
"    border-radius: .3em;\n"
"    */\n"
"}\n"
".colorPicker .oned .pointer {\n"
"    position: relative;\n"
"    z-index: 2;\n"
"}\n"
".colorPicker .oned .pointer .shape {\n"
"    position: absolute;\n"
"    margin-left: -1px;\n"
"    margin-top: -4px;\n"
"    height: 5px;\n"
"    border: 2px solid black;\n"
"    -moz-border-radius: 5px;\n"
"    border-radius: 5px;\n"
"}\n"
"/* gradients, tweak as needed based on which browsers you want to support */\n"
".colorPicker .oned .bg {\n"
"    background: -moz-linear-gradient(top,  #ff0000 0%, #ffff00 17%, #00ff00 33%, #00ffff 50%, #0000ff 66%, #ff00ff 83%, #ff0000 100%);\n"
"    background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#ff0000), color-stop(17%,#ffff00), color-stop(33%,#00ff00), color-stop(50%,#00ffff), color-stop(66%,#0000ff), color-stop(83%,#ff00ff), color-stop(100%,#ff0000));\n"
"    background: -webkit-linear-gradient(top,  #ff0000 0%,#ffff00 17%,#00ff00 33%,#00ffff 50%,#0000ff 66%,#ff00ff 83%,#ff0000 100%);\n"
"    background: -o-linear-gradient(top,  #ff0000 0%,#ffff00 17%,#00ff00 33%,#00ffff 50%,#0000ff 66%,#ff00ff 83%,#ff0000 100%);\n"
"    background: linear-gradient(to bottom,  #ff0000 0%,#ffff00 17%,#00ff00 33%,#00ffff 50%,#0000ff 66%,#ff00ff 83%,#ff0000 100%);\n"
"}\n"
"\n"
".colorPicker .twod .bg1 {\n"
"    z-index: 0;\n"
"    background: -moz-linear-gradient(left,  rgba(255,255,255,1) 0%, rgba(255,255,255,0) 100%);\n"
"    background: -webkit-gradient(linear, left top, right top, color-stop(0%,rgba(255,255,255,1)), color-stop(100%,rgba(255,255,255,0)));\n"
"    background: -webkit-linear-gradient(left,  rgba(255,255,255,1) 0%,rgba(255,255,255,0) 100%);\n"
"    background: -o-linear-gradient(left,  rgba(255,255,255,1) 0%,rgba(255,255,255,0) 100%);\n"
"    background: linear-gradient(to right,  rgba(255,255,255,1) 0%,rgba(255,255,255,0) 100%);\n"
"}\n"
".colorPicker .twod .bg2 {\n"
"    z-index: 1;\n"
"    background: -moz-linear-gradient(top,  rgba(0,0,0,0) 0%, rgba(0,0,0,1) 100%);\n"
"    background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,rgba(0,0,0,0)), color-stop(100%,rgba(0,0,0,1)));\n"
"    background: -webkit-linear-gradient(top,  rgba(0,0,0,0) 0%,rgba(0,0,0,1) 100%);\n"
"    background: -o-linear-gradient(top,  rgba(0,0,0,0) 0%,rgba(0,0,0,1) 100%);\n"
"    background: linear-gradient(to bottom,  rgba(0,0,0,0) 0%,rgba(0,0,0,1) 100%);\n"
"}\n"
"\n"
"#hslPicker .twod .bg1 {\n"
"    background: -moz-linear-gradient(left,  #ff0000 0%, #ffff00 17%, #00ff00 33%, #00ffff 50%, #0000ff 66%, #ff00ff 83%, #ff0000 100%);\n"
"    background: -webkit-gradient(linear, left top, right top, color-stop(0%,#ff0000), color-stop(17%,#ffff00), color-stop(33%,#00ff00), color-stop(50%,#00ffff), color-stop(66%,#0000ff), color-stop(83%,#ff00ff), color-stop(100%,#ff0000));\n"
"    background: -webkit-linear-gradient(left, #ff0000 0%,#ffff00 17%,#00ff00 33%,#00ffff 50%,#0000ff 66%,#ff00ff 83%,#ff0000 100%);\n"
"    background: -o-linear-gradient(left, #ff0000 0%,#ffff00 17%,#00ff00 33%,#00ffff 50%,#0000ff 66%,#ff00ff 83%,#ff0000 100%);\n"
"    background: linear-gradient(to right, #ff0000 0%,#ffff00 17%,#00ff00 33%,#00ffff 50%,#0000ff 66%,#ff00ff 83%,#ff0000 100%);\n"
"}\n"
"\n"
"#hslPicker .twod .bg2 {\n"
"    background: -moz-linear-gradient(top,  rgba(0,0,0,0) 0%, rgba(127,127,127,1) 100%);\n"
"    background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,rgba(0,0,0,0)), color-stop(100%,rgba(127,127,127,1)));\n"
"    background: -webkit-linear-gradient(top,  rgba(0,0,0,0) 0%,rgba(127,127,127,1) 100%);\n"
"    background: -o-linear-gradient(top,  rgba(0,0,0,0) 0%,rgba(127,127,127,1) 100%);\n"
"    background: linear-gradient(to bottom,  rgba(0,0,0,0) 0%,rgba(127,127,127,1) 100%);\n"
"}\n"
"\n"
"#hslPicker .oned .bg {\n"
"    z-index: 1;\n"
"    background: -moz-linear-gradient(top, rgba(255,255,255,1) 0%, rgba(0,0,0,0) 50%, rgba(0,0,0,1) 100%);\n"
"    background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,rgba(255,255,255,1)), color-stop(50%,rgba(0,0,0,0)), color-stop(100%,rgba(0,0,0,1)));\n"
"    background: -webkit-linear-gradient(top,  rgba(255,255,255,1) 0%,rgba(0,0,0,0),rgba(0,0,0,1) 100%);\n"
"    background: -o-linear-gradient(top,  rgba(255,255,255,1) 0%,rgba(0,0,0,0) 50%,rgba(0,0,0,1) 100%);\n"
"    background: linear-gradient(to bottom,  rgba(255,255,255,1) 0%,rgba(0,0,0,0) 50%,rgba(0,0,0,1) 100%);\n"
"}\n"
"\n"
"#hslPicker .extras {\n"
"    width: 100px;\n"
"}\n"
"\n"
"#hslPicker .oned.alpha {\n"
"    margin: 0;\n"
"}\n"
"\n"
"#hslPicker .oned.alpha .bg {\n"
"    background: -moz-linear-gradient(top, rgba(255,255,255,1) 0%, rgba(0,0,0,1) 100%); /* FF3.6+ */\n"
"    background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,rgba(255,255,255,1)), color-stop(100%,rgba(0,0,0,1))); /* Chrome,Safari4+ */\n"
"    background: -webkit-linear-gradient(top, rgba(255,255,255,1) 0%,rgba(0,0,0,1) 100%); /* Chrome10+,Safari5.1+ */\n"
"    background: -o-linear-gradient(top, rgba(255,255,255,1) 0%,rgba(0,0,0,1) 100%); /* Opera 11.10+ */\n"
"    background: linear-gradient(to bottom, rgba(255,255,255,1) 0%,rgba(0,0,0,1) 100%); /* W3C */\n"
"}\n"
"</style><style>    /*START OF COLORPICKER CONFIG */\n"
"    body {\n"
"        background: #eeeeee;\n"
"        margin: 20px;\n"
"      }\n"
"  \n"
"  \n"
"      .colorPicker .oned {\n"
"        margin-right: 0;\n"
"      }\n"
"  \n"
"      .colorPicker_container {\n"
"        display: flex;\n"
"        flex-direction: row;\n"
"        flex-wrap: wrap;\n"
"        padding: 20px;\n"
"        background: #ffffff;\n"
"        border-radius: 5px;\n"
"      }\n"
"\n"
"      section {\n"
"        padding: 20px;\n"
"        margin: 5px;\n"
"        background: #ffffff;\n"
"        border-radius: 5px;\n"
"        box-shadow: 0 0 10px rgba(0, 0, 0, 0.15);\n"
"      }\n"
"      .color-buttons {\n"
"        display:flex;\n"
"    }\n"
"\n"
"    .saved-color-container {\n"
"        display:flex;\n"
"        flex-flow: row wrap;\n"
"        justify-content: space-around;\n"
"        min-width: 100%;\n"
"    }\n"
"    .saved-color-title {\n"
"      text-align: center;\n"
"      padding: 15px 0;\n"
"      width: 100%;\n"
"      font-family: sans-serif;\n"
"      font-weight: bold;\n"
"    }\n"
"  \n"
"      .config {\n"
"        flex-grow: 1;\n"
"        flex-direction: column;\n"
"        margin-left: 20px;\n"
"      }\n"
"  \n"
"      .config-title {\n"
"        text-align: center;\n"
"        padding: 15px 0;\n"
"        font-family: sans-serif;\n"
"        font-weight: bold;\n"
"      }\n"
"\n"
"  \n"
"      #selected-color-text {\n"
"        text-align: center;\n"
"        margin-top: 5px;\n"
"        margin-right: 5px;\n"
"        font-family: monospace;\n"
"        font-size: 1.2em;\n"
"      }\n"
"  \n"
"      .selected-color{\n"
"        height: 30px;\n"
"        width: 50%;\n"
"        border: 1px solid #eeeeee;\n"
"        border-radius: 3px;\n"
"        cursor: pointer;\n"
"      }\n"
"      .saved-color {\n"
"        height: 50px;\n"
"        flex-grow: 1;\n"
"        border: 1px solid black;\n"
"        border-radius: 3px;\n"
"        cursor: pointer;\n"
"        float: left;\n"
"      }\n"
"\n"
"      .save-color-button {\n"
"        height: 50px;\n"
"        flex-grow: 1;\n"
"        border: 1px solid black;\n"
"        margin: 2px;\n"
"        background-color: green;\n"
"        border-radius: 3px;\n"
"        cursor: pointer;\n"
"        font-size: 20px;\n"
"        color: white;\n"
"      }\n"
"      .delete-color-button {\n"
"        height: 50px;\n"
"        flex-grow: 1;\n"
"        border: 1px solid black;\n"
"        margin: 2px;\n"
"        background-color: #d81313;\n"
"        border-radius: 3px;\n"
"        cursor: pointer;\n"
"        font-size: 20px;\n"
"        color: white;\n"
"      }\n"
"      .clear-colors-button {\n"
"        height: 50px;\n"
"        flex-grow: 1;\n"
"        border: 1px solid black;\n"
"        margin: 2px;\n"
"        background-color: #c4d813;\n"
"        border-radius: 3px;\n"
"        cursor: pointer;\n"
"        font-size: 20px;\n"
"        color: black;\n"
"      }\n"
"  \n"
"      .saved-color:not(:last-of-type) {\n"
"        margin-bottom: 5px;\n"
"        border: 1px solid black;\n"
"        flex-grow: 1;\n"
"      }\n"
"  \n"
"      /*END OF COLORPICKER CONFIG */\n"
"\n"
"/* overwrite colorjoe.css properties for proper scaling in mobile */\n"
"    #colorPicker_popup {\n"
"        display: flex;\n"
"        justify-content: center; /* Center the content horizontally */\n"
"        align-items: center; /* Center the content vertically */\n"
"        height: 100vh; /* Set height to full viewport height */\n"
"    }\n"
"    \n"
"    .colorPicker_container {\n"
"        display: flex;\n"
"        flex-direction: column; /* Stack children vertically */\n"
"        align-items: center; /* Center children horizontally */\n"
"    }\n"
"    \n"
"    .colorPicker {\n"
"        /* Keep your existing styles */\n"
"    }\n"
"    \n"
"    .twod,\n"
"    .oned {\n"
"        width: 100%; /* Occupy the full width of the parent container */\n"
"        box-sizing: border-box; /* Include padding and border in the element's total width and height */\n"
"        margin: 0.5em 0; /* Adjust margin for spacing between elements */\n"
"    }\n"
"    \n"
"    .twod .bg,\n"
"    .oned .bg,\n"
"    .oned .pointer .shape {\n"
"        width: 100%; /* Occupy the full width of the parent container */\n"
"        box-sizing: border-box; /* Include padding and border in the element's total width and height */\n"
"    }\n"
"    \n"
"    @media (min-width: 600px) {\n"
"        .twod,\n"
"        .oned,\n"
"        .twod .bg,\n"
"        .oned .bg,\n"
"        .oned .pointer .shape {\n"
"            width: 240px; /* Default width for larger screens */\n"
"        }\n"
"    }</style><style>/* Style for the buttons container */\n"
"#profileManagement div {\n"
"  display: flex;\n"
"  justify-content: center;\n"
"  flex-wrap: wrap;\n"
"  margin-top: 10px;\n"
"}\n"
"\n"
"/* Style for the buttons in the second div */\n"
".button {\n"
"  font-size: 16px;\n"
"  padding: 10px;\n"
"  margin: 5px;\n"
"  cursor: pointer;\n"
"  width: calc(30% - 10px);\n"
"  box-sizing: border-box;\n"
"}\n"
"\n"
"/* Style for the user profile buttons container */\n"
"#profiles {\n"
"  display: flex;\n"
"  flex-wrap: wrap;\n"
"  justify-content: center;\n"
"}\n"
"\n"
"/* Style for the user profile buttons */\n"
".Profile {\n"
"  font-size: 20px;\n"
"  padding: 15px 20px; /* Adjust padding for a larger button */\n"
"  margin: 5px;\n"
"  cursor: pointer;\n"
"  width: calc(20% - 10px); /* Adjust width for a larger button */\n"
"  box-sizing: border-box;\n"
"}\n"
"\n"
"/* Specific styles for different profile states */\n"
".InactiveProfile {\n"
"  background-color: gray;\n"
"}\n"
"\n"
".ActiveProfile {\n"
"  background-color: #4CAF50;\n"
"}\n"
"\n"
".SelectedProfile {\n"
"  padding: 20px 20px;\n"
"}\n"
"\n"
".LoadedProfile {\n"
"  background-color: green;\n"
"}\n"
"\n"
"\n"
"/* Style for the buttons container */\n"
"#profileManagement div {\n"
"  display: flex;\n"
"  justify-content: center;\n"
"  flex-wrap: wrap;\n"
"  margin-top: 10px;\n"
"}\n"
"\n"
"/* Style for the profile buttons container */\n"
"#profileButtons {\n"
"  display: flex;\n"
"  justify-content: center;\n"
"  flex-wrap: wrap;\n"
"  margin-top: 10px;\n"
"}\n"
"\n"
"/* Style for the buttons in the profileButtons container */\n"
".button {\n"
"  font-size: 16px;\n"
"  padding: 10px;\n"
"  margin: 5px;\n"
"  cursor: pointer;\n"
"  width: 30%; /* Set the width to 30% without calc */\n"
"  box-sizing: border-box;\n"
"}\n"
"\n"
"/* Style for the presets container */\n"
"#profilePresets {\n"
"  display: flex;\n"
"  flex-wrap: wrap;\n"
"  justify-content: center;\n"
"  margin-top: 10px;\n"
"}\n"
"\n"
"/* Style for the preset buttons in the profilePresets container */\n"
".preset {\n"
"  font-size: 16px;\n"
"  padding: 10px;\n"
"  margin: 5px;\n"
"  cursor: pointer;\n"
"  width: calc(90% - 10px); /* Set the width to 100% with margins taken into account */\n"
"  box-sizing: border-box;\n"
"}\n"
"</style><style>/* Popup styling */\n"
".popup {\n"
"    display: none;\n"
"    position: fixed;\n"
"    top: 50%;\n"
"    left: 50%;\n"
"    transform: translate(-50%, -50%);\n"
"    padding: 20px;\n"
"    background: #fff;\n"
"    border: 1px solid #ccc;\n"
"    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\n"
"    z-index: 1000;\n"
"}\n"
"\n"
"/* Media query for smaller screens */\n"
"@media screen and (max-width: 600px) {\n"
"    .popup {\n"
"        padding: 10px; /* Adjust padding for smaller screens */\n"
"        width: 80%; /* Adjust width for smaller screens */\n"
"    }\n"
"\n"
"    .attribute {\n"
"        margin-bottom: 8px;\n"
"    }\n"
"\n"
"    /* Add more adjustments as needed for smaller screens */\n"
"}\n"
"\n"
"\n"
"/* Style for the ripple container */\n"
"#ripplesList {\n"
"    display: flex;\n"
"    flex-wrap: wrap;\n"
"    justify-content: center; /* Center the ripples horizontally */\n"
"}\n"
"\n"
"/* Style for each ripple */\n"
".ripple {\n"
"    margin: 10px;\n"
"    padding: 15px;\n"
"    background-color: #f0f0f0;\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 8px;\n"
"    position: relative;\n"
"    display: flex;\n"
"    flex-direction: column;\n"
"    justify-content: space-between; /* To push the display to the bottom */\n"
"    width: calc(20% - 20px); /* Adjust the width for up to 5 ripples per row with margins taken into account */\n"
"    box-sizing: border-box; /* Include padding and border in the width calculation */\n"
"}\n"
"\n"
"/* Style for the display element inside each ripple */\n"
".ripple .display {\n"
"    padding: 10px;\n"
"    background-color: #ddd;\n"
"    border-radius: 4px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"/* Colored box in the display element */\n"
".ripple .display .color-box {\n"
"    width: 50px;\n"
"    height: 20px;\n"
"    display: inline-block;\n"
"    margin-right: 1px;\n"
"    vertical-align: middle;\n"
"    border: 2px solid #aaa;\n"
"    border-radius: 1px;\n"
"}\n"
"\n"
"/* Style for buttons inside each ripple */\n"
".ripple button {\n"
"    margin-top: 5px;\n"
"}\n"
"\n"
"/* Style for the Add Ripple button */\n"
"#addButton,\n"
"#clearAllButton {\n"
"    width: calc(50% - 20px); /* Make buttons take up half the width with margins taken into account */\n"
"    margin: 10px;\n"
"    box-sizing: border-box; /* Include padding and border in the width calculation */\n"
"}\n"
"\n"
"/* Media query for mobile devices */\n"
"@media only screen and (max-width: 767px) {\n"
"    .ripple {\n"
"        width: calc(50% - 20px); /* Adjust the width for 2 ripples per row on mobile */\n"
"    }\n"
"}\n"
"\n"
"\n"
"\n"
"/* Button styling */\n"
"button {\n"
"    padding: 10px;\n"
"    margin: 5px;\n"
"    cursor: pointer;\n"
"    background-color: #3498db;\n"
"    color: #fff;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* Edit and Delete button styling */\n"
".editButton {\n"
"    background-color: #2ecc71;\n"
"}\n"
"\n"
".deleteButton {\n"
"    background-color: #e74c3c;\n"
"}\n"
"\n"
"/* Style for the Clear All button */\n"
"#clearAllButton {\n"
"    padding: 10px;\n"
"    margin: 10px;\n"
"    cursor: pointer;\n"
"    background-color: #e74c3c; /* Red color for emphasis */\n"
"    color: #fff;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"\n"
"/* Style for attribute container */\n"
".attribute {\n"
"    display: flex;\n"
"    align-items: left;\n"
"    justify-content: left;\n"
"    margin-bottom: 10px;\n"
"    text-align: left;\n"
"}\n"
"\n"
"/* Style for the checkbox */\n"
".attribute input {\n"
"    margin-left: 5px;\n"
"    align-items: right;\n"
"}\n"
"\n"
"/* Add this style for disabled attributes */\n"
".attribute input:not(:checked) + span {\n"
"    color: #888;\n"
"}\n"
"\n"
".attribute input:not(:checked) + span + * {\n"
"    pointer-events: none;\n"
"    background-color: #eee;\n"
"}\n"
"  \n"
"  /* Style for the checkbox */\n"
"  .attribute input {\n"
"    margin-right: 10px;\n"
"  }\n"
"\n"
"/* Style for buttons */\n"
".buttons {\n"
"    margin-top: 10px;\n"
"}\n"
"\n"
"/* Style for the Add Ripple button */\n"
"#addButton {\n"
"    padding: 10px;\n"
"    margin: 10px 0;\n"
"    cursor: pointer;\n"
"    background-color: #3498db;\n"
"    color: #fff;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"/* Style for the color input */\n"
"input[type='color'] {\n"
"    width: 30px;\n"
"    height: 30px;\n"
"    padding: 0;\n"
"    margin: 0;\n"
"}\n"
"\n"
"/* Add more specific styles as needed for your application */\n"
"/* Style for the user input buttons container */\n"
"#userinputButtons {\n"
"    text-align: center;\n"
"    display: flex;\n"
"    flex-direction: row;\n"
"    justify-content: center;\n"
"  }\n"
"  \n"
"  /* Style for the user input buttons */\n"
"  .userinputButton {\n"
"    font-size: 16px;\n"
"    padding: 10px;\n"
"    margin: 5px;\n"
"    cursor: pointer;\n"
"    width: 150px; /* You can adjust the width as needed */\n"
"    box-sizing: border-box;\n"
"  }\n"
"  </style>";

#endif /* HTTP_SERVER_CSS_H */
